#!/usr/bin/env bash
  
PROMPT_COMMAND=__prompt_command

__prompt_command() {
  local EXIT="$?"

  PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]'

  local Red='\[\e[0;31m\]'
  if [ $EXIT != 0 ]; then
    PS1+="${Red}\$ ";
  else
    PS1+="\$ ";
  fi

  PS1+="\[\033[00m\]";
}
